### ISSUE TITLE
Clarify the differences between this fork and the original

### ISSUE THREAD

**Issue by m040601** [techknowlogick/shiori#125]
Thank you for your work in this project. I like this project a lot. Although not a developer, I can contribute with testing, feedback and a package for a Linux distro.

Could you clarify a little better:
- what are the differences and the goals of your fork compared to the original ? 
- Is there any contact between the two ?
- is the original Shiori not being updated anymore, https://github.com/RadhiFadlillah/shiori ?

I've already read the issue, https://github.com/techknowlogick/shiori/issues/82,
"Document changes with original project" but I'm not sure.

UPDATE: just read, https://github.com/RadhiFadlillah/shiori/issues/119

> 
> ...I will start working on shiori again....
> ..@techknowlogick thanks for forking this project ...
> ...will cherry-picks some of your improvements, especially those that related to front-end since I'm quite lacking on that part....

- Maybe you could add some of this information to the Readme.md front page. To make it clear where can one contribute or give feedback ?

**Comment by techknowlogick** [comment]
@m040601 Thanks for the questions. I've updated the readme with that information.
