### ISSUE TITLE
Update fails due to incorrect column name: bookmark_id should be id

### ISSUE THREAD

**Issue by NiceGuyIT** [techknowlogick/shiori#242]
From [comment](https://github.com/techknowlogick/shiori/issues/9#issuecomment-472403128):
> Things that don't work in the Webinterface:
> * Edit a Bookmark Title

This is because the column name is incorrect. Unfortunately, `SHIORI_SHOW_SQL=true` doesn't show the error. I couldn't find a way to log the SQL error outside changing the code. However, entering the SQL in MySQL gives the error message that the column doesn't exist.

```diff
diff --git a/database/xorm.go b/database/xorm.go
index 0255e6b..c0031fd 100644
--- a/database/xorm.go
+++ b/database/xorm.go
@@ -191,7 +191,7 @@ func (db *XormDatabase) UpdateBookmarks(bookmarks ...model.Bookmark) (result []m
        }
        for _, bookmark := range bookmarks {
                // create bookmark & get ID
-               session.Where("bookmark_id = ?", bookmark.ID).Update(&bookmark)
+               session.Where("id = ?", bookmark.ID).Update(&bookmark)
                // clear existing tag assignments
                session.Where("bookmark_id = ?", bookmark.ID).Delete(&model.BookmarkTag{})
                // insert & assign tag assignments
```

**Comment by techknowlogick** [comment]
Thanks for debugging this 😃. I've just merged the change in your diff.
