### ISSUE TITLE
Doesn't compile with go 1.13

### ISSUE THREAD

**Issue by munntjlx** [techknowlogick/shiori#308]
I get the following error when doing "go build" 

go: github.com/asaskevich/govalidator@v0.0.0-20190207205813-f9ffefc3facf: invalid pseudo-version: does not match version-control timestamp (2018-07-20T11:50:03Z)****

**Comment by munntjlx** [comment]
Also tried with official docker image same result 

o: finding github.com/gin-gonic/contrib 35076c1b2bea
go: finding github.com/go-shiori/go-readability 9a7f6996b6cc
go: finding github.com/mattn/go-sqlite3 v2.0.2
go: finding golang.org/x/crypto 497ca9f6d64f
go: github.com/asaskevich/govalidator@v0.0.0-20190207205813-f9ffefc3facf: invalid pseudo-version: does not match version-control timestamp (2018-07-20T11:50:03Z)
root@9157d0d11686:/go/shiori#

**Comment by munntjlx** [comment]
As a fun aside, the docker version is also broken now: (on mac / docker at least!)

`go: finding github.com/denisenkom/go-mssqldb cfbb681360f0
go: finding github.com/gin-gonic/contrib 35076c1b2bea
go: finding github.com/go-shiori/go-readability 9a7f6996b6cc
go: finding github.com/mattn/go-sqlite3 v2.0.2
go: finding golang.org/x/crypto 497ca9f6d64f
go: github.com/asaskevich/govalidator@v0.0.0-20190207205813-f9ffefc3facf: invalid pseudo-version: does not match version-control timestamp (2018-07-20T11:50:03Z)
`

**Comment by munntjlx** [comment]
I also guess the build server is mad since I just noticed the build server can't build it either.

**Comment by munntjlx** [comment]
I love shiori. Please fix (as you have time trying to be nice and actually say please!)

**Comment by munntjlx** [comment]
Anything I can do to help? Alas I am not a coder, but I will be happy to be your guinea-build-bot.

**Comment by techknowlogick** [comment]
Thanks for attempting to debug, seems some upstream libraries have changed even when I pinned specific versions.

I've gone through and made an update, and now it compiles under go1.13. 

I will close this now, but please re-open if you still have issues. Thanks :)

**Comment by munntjlx** [comment]
thanks for closing. It works fine now on mac, and on linux and on docker.
