### ISSUE TITLE
upstream support status changed

### ISSUE THREAD

**Issue by clach04** [techknowlogick/shiori#365]
I stumbled across your repo after spending time getting the upstream version for Raspberry Pi.

Probably worth updating the readme to mention change in status as current readme recommends checking out the upstream version. As upstream is archived its not possible top update existing issues or open new ones.

**Comment by techknowlogick** [comment]
Thanks for the report :)

I will update that now.

**Comment by techknowlogick** [comment]
Closed with https://github.com/techknowlogick/shiori/commit/af4eaa8626782f5d937e1fea059513a97d2ef5ed
