### ISSUE TITLE
Document using other DBs

### ISSUE THREAD

**Issue by techknowlogick** [techknowlogick/shiori#9]

**Comment by m0veax** [comment]
Did I understood it correctly that choosing a DB is default to sqlite and otherwise there are Environment Variables to override this?

I plan to install your fork soon on MySQL and would document that right away afterwards.

My golang foo is not the best, so I wanted to make sure I understood that correctly

**Comment by techknowlogick** [comment]
@m0veax that’s correct. It defaults to sqlite, but then you can change it to MySQL, postgresql, mssql, and others.

**Comment by techknowlogick** [comment]
I’m on mobile right now but can give you instructions soon.

**Comment by techknowlogick** [comment]
To use mysql, you'll need to set the following environment variables
```
SHIORI_DBTYPE=mysql
SHIORI_DSN=user:password@localhost/databasename?charset=utf8mb4&parseTime=True&loc=Local
```
where you'll need to set username, password, host, and database name in the second environment.

Please let me know if that doesn't work for you.

**Comment by m0veax** [comment]
Thanks for your insights, i tried to install shiori on my box today.

I build shiori successfully with go 1.11.2 and build a wrapper script for providing env variables.

Somehow i get the error "ERRO[0000] [./go/bin/shiori account add accountname]: default addr for network 'localhost' unknown"

Here i provide a gist with all informations i have so far:

https://gist.github.com/m0veax/df14ba3eba37060ab970453164a9dcf4

Maybe i don't know xorm enough or it is something with my box, but i thought localhost shouldn't be a problem at all :)

**Comment by techknowlogick** [comment]
@m0veax Thank you for feedback. Sorry about the trouble. I was able to replicate and resolve. What happened was I made a typo in the example DSN. There should've been `()` around localhost.
So DSN should be: `user:password@(localhost)/db_name?charset=utf8&parseTime=True&loc=Local`

**Comment by m0veax** [comment]
That worked out great :)

Thanks, as soon as I got through the full setup process I will write up some docs

**Comment by techknowlogick** [comment]
@m0veax I found one problem with mysql thanks to this testing and I will be patching it now, please keep an eye on upcoming commits.

**Comment by m0veax** [comment]
@techknowlogick maybe you could reference this issue? Looking forward to what you found :)

**Comment by techknowlogick** [comment]
@m0veax The commit is: 4cdb1b5f6df74a41141ecf8de7bc17b588271a08 it forces the column type to be text. For sqlite and postgresql it is that already but mysql defaulted to using varchar(255), and for storing long snippets of HTML that failed.

**Comment by m0veax** [comment]
@techknowlogick

Thanks, just started a new build per:

    go get -u src.techknowlogick.com/shiori

**Comment by m0veax** [comment]
How to force migrations to run? Just calling the app didn't helped.

The html column is still a varchar.

I'll add this to the docs too.

Edit: I realized that I have to take care of this by myself, but maybe this would be a good feature for the future.

I am on mobile and alter tables are a bit hard right now. I'll test this tommorow

Edit2: adding a bookmark helped ..

Forget about that feature request :) it's already part of the application

**Comment by techknowlogick** [comment]
This line here should auto-migrate: https://github.com/techknowlogick/shiori/blob/master/database/xorm.go#L33 but proper migrations are indeed needed.

**Comment by m0veax** [comment]
Yeah it did, I wasn't aware that xorm has such a feature. Awesome!

I need to do more go :)

**Comment by m0veax** [comment]
I am still doing something wrong somewhere. I started

    shiori serve -p 36362

But if I access the Webinterface I get following message:

    stat /dist/login.html: no such file or directory

Sorry for all the traffic here, but I will add it all to the docs in exchange :)

I can open a separate issue if you want too?

Edit: my shiori files are at

    ~/go/src/src.techknowlogick.com/shiori

**Comment by techknowlogick** [comment]
That's ok. I don't mind the questions, as it does help build out documentation.

Unlike the original project that has all the assets built in, this one requires a bit more work to get started. It was a trade-off that I weighed the pros/cons of. Cons: harder to get started. Pros: Easier to manager dependencies, easier to update, smaller repo. So to embed assets into the binary I use the library [packr2](https://github.com/gobuffalo/packr) to embed assets into the binary that are fetched & built by nodejs

To build I use the following command:
```
GO111MODULE=on make dep build
```
This can be broken down into multiple parts:
* setting the environment variable `GO111MODULE=on` allows us to use go modules as define in the `go.mod` file (so I can target a specific version of a library)
* the [dep](https://github.com/techknowlogick/shiori/blob/master/Makefile#L59) step of make is actually split into two parts, `dep-node` and `dep-go`
  * [dep-node](https://github.com/techknowlogick/shiori/blob/master/Makefile#L63)
    * ensure a specific minimum version of npm running
    * installs all resources as required by [package.json](https://github.com/techknowlogick/shiori/blob/master/package.json)
    * builds the final JS/CSS files (that are minified for performance)
    * finally runs some cleanup on the output to ensure that any paths in the dist directory refer to it as absolute.
  * [dep-go](https://github.com/techknowlogick/shiori/blob/master/Makefile#L72)
    * ensures that packr2 binary can be called
    * runs packr2 to generate go files that embed all files in the `dist` directory (note: for development you may not want to run this step so that when rebuilding CSS/JS files then you can restart the binary to get latest files)
* the [build](https://github.com/techknowlogick/shiori/blob/master/Makefile#L50) make step essentially runs `go build` with a few extra flags to embed version information and a few other tweaks.

Once that above command is run you'll have a shiny new binary `shiori` in the directory that you ran the above command in that has all the CSS/JS/HTML embeded in it.

**Comment by m0veax** [comment]
Is it right, that I can't use `go get -u` this way?

I have to check the repository out and start from there?

I will try it today

**Comment by techknowlogick** [comment]
That is correct, `go get -u -d src.techknowlogick.com/shiori` should be used instead so code can be fetched & updated but not installed.

**Comment by m0veax** [comment]
OK, i was able to do this steps :)

But now i am pointing following problem:

    go build github.com/gobuffalo/packr/v2/file/resolver/encoding/hex: module requires Go 1.12
    go build golang.org/x/sys/unix: module requires Go 1.12
    go build github.com/gobuffalo/packr/v2/file: module requires Go 1.12
    make: *** [dep-go] Error 1

I will try to upgrade to golang 1.12. now

EDIT: I have some trouble with linuxbrew that i have to solve first for upgrading to Go 1.12

I will let you know as soon as i can continue here

**Comment by m0veax** [comment]
What a ride...

After a greater config session involving to provide gcc for my user on my shared host and building go 1.12. per linuxbrew on my box, I was able to install the packr2 binary and the right nodejs version.

Last but not least I was able to build shiori with your command and serve does now work as expected!

Thanks for that, I will try to document that all the next days and will create a PR then.

**Comment by m0veax** [comment]
One little last thing I am trying to figure out is serving shiori behind an Apache proxy config in a subfolder like `http://example.com/bookmarks`.

But that is a story for another day :)

**Comment by m0veax** [comment]
Well, a reverse proxy per subdomain works. Is there anything i need to do, to enable shiori to make shiori writing in the fields "html" and "image_url"?

I can use the Webinterface now, but gathering cache data is not happening right now.

EDIT: Ah OK, it only take images if there are images. I thought about Screenshots :)

**Comment by m0veax** [comment]
I guess I found a bug while using Shiori with MySQL (idk if it is the same for another DBs).

Things that don't work in the Webinterface:

- Edit a Bookmark Title
- removing a Tag from a Bookmark

The API responds with HTTP 200 and a updated JSON Object, but the change is not written to the Database at all.

Can i provide more Informations? The serve command does not output anything related at all.

**Comment by m0veax** [comment]
Well after merging the PR, let's close this one and I will add a new issue with an sql log regarding the problems I described above :)

**Comment by techknowlogick** [comment]
Sounds good. Thanks again :)
